Update rdpgui

diff --git a/rdpgui b/rdpgui
--- a/rdpgui
+++ b/rdpgui
@@ -19,16 +19,16 @@ export HOME=${HOME:-/root}
 # screen.d/rdesktop to screen.d/xfreerdp.
 basename=${0##*/}
 
-#if ! type $basename >/dev/null 2>&1; then
-#    echo "$basename couldn't be found."
-#    if [ "$basename" = "rdesktop" ]; then
-#        echo "Some distributions have now switched to 'xfreerdp' instead of 'rdesktop'."
-#        echo "You may want to change your SCREEN_XX entry to that instead."
-#        echo "Please note that RDP_OPTIONS will need updating for xfreerdp."
-#    fi
-#    read nothing
-#    exit 1
-#fi
+if ! type $basename >/dev/null 2>&1; then
+    echo "$basename couldn't be found."
+    if [ "$basename" = "rdesktop" ]; then
+        echo "Some distributions have now switched to 'xfreerdp' instead of 'rdesktop'."
+        echo "You may want to change your SCREEN_XX entry to that instead."
+        echo "Please note that RDP_OPTIONS will need updating for xfreerdp."
+    fi
+    read nothing
+    exit 1
+fi
 
 # Make XINITRC_DAEMON default to "True", to prevent X from restarting after
 # logout. If you don't want that, force XINITRC_DAEMON=False in lts.conf.
@@ -36,11 +36,20 @@ export XINITRC_DAEMON="${XINITRC_DAEMON-True}"
 
 # If no parameters were passed, set some reasonable defaults.
 if [ -z "$*" ]; then
-    RDP_OPTIONS=${RDP_OPTIONS:-"-f -u ''"}
-    RDP_SERVER=${RDP_SERVER:-"server"}
+	case $basename in
+		rdesktop)
+			RDP_OPTIONS=${RDP_OPTIONS:-"-f -u ''"}
+			RDP_SERVER=${RDP_SERVER:-"server"}
+			;;
+		*)
+			RDP_OPTIONS=${RDP_OPTIONS:-"/f"}
+			RDP_SERVER=/v:${RDP_SERVER:-"server"}
+			;;
+	esac
 fi
 
-COMMAND="/usr/share/ltsp/screen.d/xfreerdp-prompt $RDP_OPTIONS $RDP_SERVER"
+
+COMMAND="/usr/share/ltsp/screen.d/xfreerdp-prompt $* $RDP_OPTIONS $RDP_SERVER"
 
 # The following logic is described at the top of xinitrc.
 exec xinit /usr/share/ltsp/xinitrc "$COMMAND" -- "$DISPLAY" "vt${TTY}" -nolisten tcp $X_ARGS >/dev/null
